# Generated by Django 2.2.6 on 2020-02-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_auto_20181204_0441'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memoire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('student', models.CharField(max_length=100, verbose_name='student')),
                ('summary', models.TextField(max_length=1000, verbose_name='Résumé')),
            ],
        ),
        migrations.CreateModel(
            name='sout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('student', models.CharField(max_length=300)),
                ('summary', models.TextField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='book',
            name='language',
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=100, verbose_name='Auteur'),
        ),
        migrations.AlterField(
            model_name='book',
            name='available_copies',
            field=models.IntegerField(verbose_name='copy disponible'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='book_image', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.TextField(help_text='Enter une description pour le livre', max_length=1000, verbose_name='sommaire'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='book',
            name='total_copies',
            field=models.IntegerField(verbose_name='total copies'),
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(max_length=3, verbose_name='Niveau'),
        ),
        migrations.AlterField(
            model_name='student',
            name='contact_no',
            field=models.CharField(max_length=10, verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=10, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='student',
            name='pic',
            field=models.ImageField(blank=True, upload_to='profile_image', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.CharField(max_length=10, unique=True, verbose_name='Id_etud'),
        ),
        migrations.AlterField(
            model_name='student',
            name='total_books_due',
            field=models.IntegerField(default=0, verbose_name='Total livres'),
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
