# Generated by Django 2.2.6 on 2020-02-01 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_auto_20200201_1259'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sout',
        ),
    ]
